name: Build and Release EXE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: pyinstaller client.py

      - name: Archive EXE
        run: Compress-Archive -Path dist\ -DestinationPath release.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Auto Release ${{ github.run_number }}"
          tag_name: "v${{ github.run_number }}"
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}