name: Build and Release EXE

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: pyinstaller client.py

      - name: Copy helper scripts
        run: |
          cp .\dist\run.bat .\dist\client\
          cp .\dist\run.ps1 .\dist\client\
          cp .\windows_run_as_admin.ps1 .\dist\client\

      - name: Archive EXE
        run: Compress-Archive -Path dist\ -DestinationPath release.zip

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} "release.zip" --generate-notes --title "release-${{ github.ref_name }}"

